"use client";

import { useEffect, useRef, useState } from "react";
import type { Components } from "react-markdown";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { getHighlighter } from "@/lib/shiki-singleton";

/**
 * Props for MarkdownRenderer component
 */
interface MarkdownRendererProps {
	/** Markdown content to render */
	content: string;
	/** Additional CSS classes for the container */
	className?: string;
}

/**
 * Code block with copy button and language label
 */
function CodeBlockWithCopy({
	html,
	language,
}: {
	html: string;
	language: string;
}) {
	const [copied, setCopied] = useState(false);
	const containerRef = useRef<HTMLDivElement>(null);

	const handleCopy = () => {
		// Extract code from the shiki-rendered HTML
		const codeElement = containerRef.current?.querySelector("code");
		if (codeElement) {
			const code = codeElement.textContent || "";
			navigator.clipboard.writeText(code);
			setCopied(true);
			setTimeout(() => setCopied(false), 2000);
		}
	};

	// Format language name for display
	const displayLanguage =
		language === "text"
			? ""
			: language.charAt(0).toUpperCase() + language.slice(1);

	return (
		<div ref={containerRef} className="relative group">
			{/* Language label - uses CSS variables for theme support */}
			{displayLanguage && (
				<div
					className="absolute top-2 left-2 px-2 py-0.5 rounded text-xs font-medium bg-[var(--color-surface-elevated)] text-[var(--color-text-secondary)]"
				>
					{displayLanguage}
				</div>
			)}
			{/* Copy button */}
			<button
				type="button"
				onClick={handleCopy}
				className="absolute top-2 right-2 p-1.5 bg-[var(--color-border)] hover:bg-[var(--color-text-muted)] text-[var(--color-text-primary)] rounded opacity-0 group-hover:opacity-100 transition-opacity text-xs z-10"
				aria-label="Copy code"
			>
				{copied ? (
					<svg
						className="w-4 h-4"
						fill="none"
						stroke="currentColor"
						viewBox="0 0 24 24"
						aria-hidden="true"
					>
						<title>Copied</title>
						<path
							strokeLinecap="round"
							strokeLinejoin="round"
							strokeWidth={2}
							d="M5 13l4 4L19 7"
						/>
					</svg>
				) : (
					<svg
						className="w-4 h-4"
						fill="none"
						stroke="currentColor"
						viewBox="0 0 24 24"
						aria-hidden="true"
					>
						<title>Copy</title>
						<path
							strokeLinecap="round"
							strokeLinejoin="round"
							strokeWidth={2}
							d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
						/>
					</svg>
				)}
			</button>
			<div
				// biome-ignore lint/security/noDangerouslySetInnerHtml: HTML is generated by Shiki, a trusted syntax highlighter
				dangerouslySetInnerHTML={{ __html: html }}
				className="shiki-code-block"
			/>
		</div>
	);
}

/**
 * Base components without syntax highlighting
 */
const baseComponents: Components = {
	// Links
	a: ({ children, href, ...props }) => (
		<a
			href={href}
			className="text-[var(--color-primary)] hover:text-[var(--color-primary-hover)] underline"
			target="_blank"
			rel="noopener noreferrer"
			{...props}
		>
			{children}
		</a>
	),
	// Paragraphs
	p: ({ children, ...props }) => (
		<p className="text-[var(--color-text-primary)]" {...props}>
			{children}
		</p>
	),
	// Lists
	ul: ({ children, ...props }) => (
		<ul className="text-[var(--color-text-primary)]" {...props}>
			{children}
		</ul>
	),
	ol: ({ children, ...props }) => (
		<ol className="text-[var(--color-text-primary)]" {...props}>
			{children}
		</ol>
	),
	// List items
	li: ({ children, ...props }) => (
		<li className="text-[var(--color-text-primary)]" {...props}>
			{children}
		</li>
	),
	// Headings
	h1: ({ children, ...props }) => (
		<h1 className="text-[var(--color-text-primary)] font-bold" {...props}>
			{children}
		</h1>
	),
	h2: ({ children, ...props }) => (
		<h2 className="text-[var(--color-text-primary)] font-bold" {...props}>
			{children}
		</h2>
	),
	h3: ({ children, ...props }) => (
		<h3 className="text-[var(--color-text-primary)] font-bold" {...props}>
			{children}
		</h3>
	),
	h4: ({ children, ...props }) => (
		<h4 className="text-[var(--color-text-primary)] font-bold" {...props}>
			{children}
		</h4>
	),
	h5: ({ children, ...props }) => (
		<h5 className="text-[var(--color-text-primary)] font-bold" {...props}>
			{children}
		</h5>
	),
	h6: ({ children, ...props }) => (
		<h6 className="text-[var(--color-text-primary)] font-bold" {...props}>
			{children}
		</h6>
	),
};

/**
 * MarkdownRenderer - Shared markdown rendering component with Shiki syntax highlighting
 *
 * Features:
 * - GitHub Flavored Markdown (GFM) support
 * - Syntax highlighting using Shiki
 * - Copy button on code blocks
 *
 * @example
 * ```tsx
 * <MarkdownRenderer content="# Hello\n\n```js\nconsole.log('hi');\n```" />
 * ```
 */
export function MarkdownRenderer({
	content,
	className = "",
}: MarkdownRendererProps) {
	const [components, setComponents] = useState<Components>({
		...baseComponents,
		// Default pre/code before shiki loads
		pre: ({ children, ...props }) => (
			<pre
				style={{
					padding: "1rem",
					borderRadius: "0.5rem",
					whiteSpace: "pre-wrap",
					wordBreak: "break-word",
				}}
				{...props}
			>
				{children}
			</pre>
		),
		code: ({ className, children, ...props }) => {
			const isInline = !className;
			if (isInline) {
				return (
					<code
						className="bg-[var(--color-surface-elevated)] text-[var(--color-primary)] px-1.5 py-0.5 rounded text-sm font-mono"
						{...props}
					>
						{children}
					</code>
				);
			}
			return (
				<code className={className} {...props}>
					{children}
				</code>
			);
		},
	});

	useEffect(() => {
		async function loadShiki() {
			try {
				// Use singleton highlighter instead of creating new instance
				const highlighter = await getHighlighter();

				// Detect current theme from data attribute
				const isDark = document.documentElement.getAttribute("data-theme") === "dark";
				// Use catppuccin-mocha for dark theme, catppuccin-latte for light theme
				const shikiTheme = isDark ? "catppuccin-mocha" : "catppuccin-latte";

				setComponents({
					...baseComponents,
					code: ({ className, children, ...props }) => {
						const isInline = !className;
						if (isInline) {
							return (
								<code
									className="bg-[var(--color-surface-elevated)] text-[var(--color-primary)] px-1.5 py-0.5 rounded text-sm font-mono"
									{...props}
								>
									{children}
								</code>
							);
						}

						const language = className.replace(/language-/, "") || "text";
						const code = String(children).replace(/\n$/, "");

						const html = highlighter.codeToHtml(code, {
							// biome-ignore lint/suspicious/noExplicitAny: Shiki expects specific language strings, but we need to accept dynamic values
							lang: language as any,
							theme: shikiTheme,
						});

						return <CodeBlockWithCopy html={html} language={language} />;
					},
				});
			} catch (error) {
				console.error("Failed to load Shiki:", error);
			}
		}

		loadShiki();
	}, []);

	return (
		<div className={className}>
			<ReactMarkdown remarkPlugins={[remarkGfm]} components={components}>
				{content || "*Empty content*"}
			</ReactMarkdown>
		</div>
	);
}
